{
  imports = [
    ./plugins/bufferline.nix
    ./plugins/telescope.nix
    ./plugins/treesitter.nix
    ./plugins/nvim-tree.nix
    ./plugins/codeium.nix
    ./plugins/lsp.nix
    ./plugins/cmp.nix
    ./plugins/friendly-snippets.nix
    ./plugins/luasnip.nix
    ./plugins/comment.nix
    ./plugins/nvim-autopairs.nix
    ./plugins/gitsigns.nix
    ./plugins/which-key.nix
    ./plugins/project-nvim.nix
    ./plugins/lualine.nix
    ./plugins/navic.nix
    ./plugins/dap.nix
    ./plugins/alpha.nix
    ./plugins/toggleterm.nix
    ./plugins/illuminate.nix
    ./plugins/indent-blankline.nix
    ./plugins/trouble.nix
    ./plugins/lspkind.nix
    ./plugins/twilight.nix
    ./plugins/rust.nix
    ./plugins/python.nix
  ];
}
